title: Codezilla.it Web Agency
email: hey@codezilla.it
url: "http://www.codezilla.it" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Codezilla.it Site | Andrea Rabbaglietti - Fabio Cencetti
github_username:  codezilla-it
markdown: kramdown
sass_dir: "_sass"
static_path: "/static"